/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poly.cafe.ui;
/**
 *
 * @author Home
 */
public class PolyCafeJFrame extends javax.swing.JFrame {
 private boolean isManager;
    /**
     * Creates new form PolyCafeJFrame
     */
    public PolyCafeJFrame() {
        
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        configureButtons();
    }
    public void setUserRole(boolean isManager) {
        this.isManager = isManager;
        configureButtons(); // Cập nhật giao diện
    }
    void openDoiMatKhau(){
        new ChangePasswordJDialog(this, true).setVisible(true);
    }
    void openLichSu(){
        new HistoryJDialog(this, true).setVisible(true);
    }
    void openSale(){
        new SaleJDialog(this, true).setVisible(true);
    }
    void openQuanLyDoUong(){
        new DrinkManagementJDialog(this, true).setVisible(true);
    }
    void openLoaiDoUong(){
        new CategoryManagerJDialog(this, true).setVisible(true);
    }
    void openTheDinhDanh(){
        new IDCardManagementJDialog(this, true).setVisible(true);
    }
    void openPhieuBanHang(){
        new BillManagementJDialog(this, true).setVisible(true);
    }
    void openQuanLyNguoiDung(){
        new AccountManagementJDialog(this, true).setVisible(true);
    }
    void openBaoCaoThongKe(){
        new RevenueStatisticsJDialog(this, true).setVisible(true);
    }
    private void configureButtons() {
        if (isManager) {
            // hiện nút cho quản lý
            BtnDoanhThu.setVisible(true);
            BtnLoaiDoUong.setVisible(true);
            BtnDoUong.setVisible(true);
            BtnNguoiSuDung.setVisible(true);
            BtnPhieuBanHang.setVisible(true);
            BtnTheDinhDanh.setVisible(true);
            Usertxt.setText("Quản lý");
        } else {
            // ẩn nút cho nhân viên
            BtnDoanhThu.setVisible(false);
            BtnLoaiDoUong.setVisible(false);
            BtnDoUong.setVisible(false);
            BtnNguoiSuDung.setVisible(false);
            BtnPhieuBanHang.setVisible(false);
            BtnTheDinhDanh.setVisible(false);
            Usertxt.setText("Nhân viên");

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        BtnKetThuc = new javax.swing.JButton();
        BtnBanHang = new javax.swing.JButton();
        BtnLichSu = new javax.swing.JButton();
        BtnDoiMatKhau = new javax.swing.JButton();
        Usertxt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BtnTheDinhDanh = new javax.swing.JButton();
        BtnLoaiDoUong = new javax.swing.JButton();
        BtnPhieuBanHang = new javax.swing.JButton();
        BtnNguoiSuDung = new javax.swing.JButton();
        BtnDoanhThu = new javax.swing.JButton();
        BtnDoUong = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Poly Cafe");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        jPanel2.setForeground(new java.awt.Color(255, 153, 0));

        BtnKetThuc.setText("Kết thúc");
        BtnKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKetThucActionPerformed(evt);
            }
        });

        BtnBanHang.setText("Bán hàng");
        BtnBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBanHangActionPerformed(evt);
            }
        });

        BtnLichSu.setText("Lịch sử");
        BtnLichSu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLichSuActionPerformed(evt);
            }
        });

        BtnDoiMatKhau.setText("Đổi mật khẩu");
        BtnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDoiMatKhauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnDoiMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnKetThuc, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(BtnLichSu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnLichSu, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(BtnBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnKetThuc, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(BtnDoiMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Usertxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Usertxt.setForeground(new java.awt.Color(255, 0, 255));
        Usertxt.setText("Usertxt");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/avatar.png"))); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnTheDinhDanh.setText("thẻ định danh");
        BtnTheDinhDanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTheDinhDanhActionPerformed(evt);
            }
        });
        jPanel1.add(BtnTheDinhDanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 250, 79));

        BtnLoaiDoUong.setText("Loại đồ uống");
        BtnLoaiDoUong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoaiDoUongActionPerformed(evt);
            }
        });
        jPanel1.add(BtnLoaiDoUong, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 250, 79));

        BtnPhieuBanHang.setText("Phiếu bán hàng");
        BtnPhieuBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPhieuBanHangActionPerformed(evt);
            }
        });
        jPanel1.add(BtnPhieuBanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 250, 79));

        BtnNguoiSuDung.setText("Người sử dụng");
        BtnNguoiSuDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNguoiSuDungActionPerformed(evt);
            }
        });
        jPanel1.add(BtnNguoiSuDung, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 250, 79));

        BtnDoanhThu.setText("doanh thu");
        BtnDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDoanhThuActionPerformed(evt);
            }
        });
        jPanel1.add(BtnDoanhThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, 250, 79));

        BtnDoUong.setText("Đồ uống");
        BtnDoUong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDoUongActionPerformed(evt);
            }
        });
        jPanel1.add(BtnDoUong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 250, 79));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/coffee-shop.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(Usertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)))
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Usertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnDoUongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDoUongActionPerformed
        openQuanLyDoUong();
    }//GEN-LAST:event_BtnDoUongActionPerformed

    private void BtnLoaiDoUongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoaiDoUongActionPerformed
       openLoaiDoUong();
    }//GEN-LAST:event_BtnLoaiDoUongActionPerformed

    private void BtnKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKetThucActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKetThucActionPerformed

    private void BtnNguoiSuDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNguoiSuDungActionPerformed
        openQuanLyNguoiDung();
    }//GEN-LAST:event_BtnNguoiSuDungActionPerformed

    private void BtnLichSuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLichSuActionPerformed
        openLichSu();
    }//GEN-LAST:event_BtnLichSuActionPerformed

    private void BtnDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDoiMatKhauActionPerformed
        openDoiMatKhau();
    }//GEN-LAST:event_BtnDoiMatKhauActionPerformed

    private void BtnBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBanHangActionPerformed
        openSale();
    }//GEN-LAST:event_BtnBanHangActionPerformed

    private void BtnTheDinhDanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTheDinhDanhActionPerformed
        openTheDinhDanh();
    }//GEN-LAST:event_BtnTheDinhDanhActionPerformed

    private void BtnPhieuBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPhieuBanHangActionPerformed
        openPhieuBanHang();
    }//GEN-LAST:event_BtnPhieuBanHangActionPerformed

    private void BtnDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDoanhThuActionPerformed
        openBaoCaoThongKe();
    }//GEN-LAST:event_BtnDoanhThuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PolyCafeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PolyCafeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PolyCafeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PolyCafeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PolyCafeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBanHang;
    private javax.swing.JButton BtnDoUong;
    private javax.swing.JButton BtnDoanhThu;
    private javax.swing.JButton BtnDoiMatKhau;
    private javax.swing.JButton BtnKetThuc;
    private javax.swing.JButton BtnLichSu;
    private javax.swing.JButton BtnLoaiDoUong;
    private javax.swing.JButton BtnNguoiSuDung;
    private javax.swing.JButton BtnPhieuBanHang;
    private javax.swing.JButton BtnTheDinhDanh;
    private javax.swing.JLabel Usertxt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
