/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package poly.cafe.ui;

import java.awt.Frame;
import javax.swing.JOptionPane;
import poly.cafe.ui.BillJDialog;
import poly.cafe.ui.BillManagementJDialog;
import poly.cafe.entity.Cards;
import poly.cafe.entity.Bills;
import poly.cafe.entity.BillDetails;
import poly.cafe.dao.BillsManagerDao;
import poly.cafe.ui.IDCardManagementJDialog;
import poly.cafe.util.XAuth;
/**
 *
 * @author Home
 */
public class SaleJDialog extends javax.swing.JDialog {
private final Frame parentFrame; // Store the parent Frame
    /**
     * Creates new form SaleJDialog
     */
    public SaleJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.parentFrame = parent; // Save the parent Frame
        setLocationRelativeTo(null);
        
    }
  
  void openBillDialog() {
        try {
            new BillJDialog(parentFrame, true).setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error opening bill dialog: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }



//Form này có 30 button tên là BtnCard1 - BtnCard30 khi ấn vào 1 button thì lấy button từ IDCardManagerment button ở đấy có 3 trạng thái comper lose error
//khi ở trạng thái error và lose thì không thể tương tác button sẽ tối màu và không ấn được, button ở trạng thái oper thì sẽ load vào Form billJDialog với số thẻ tương ứng
//button oper có background màu xanh lá và button không màu tức là thẻ đấy chưa tồn tại trong csdl và chưa được tạo trong ICcard thì khi ấn vào sẽ tự động tạo
//thẻ trạng thái ope và khi Form Bill xuất hiện thì load số thẻ vào text Field
//id của hóa đơn chi tiết tư sinh giống hóa đơn và trong cơ sở dữ liệu ơ hóa đơn chi tiết có billid liên kết với khóa chính của id để khi 
//chuyển đến hóa đơn có mã tương ứng ở quản lý hóa đơn thì sẽ load thông tin của hóa đơn đó lên từ đó

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnCard1 = new javax.swing.JButton();
        BtnCard2 = new javax.swing.JButton();
        BtnCard3 = new javax.swing.JButton();
        BtnCard4 = new javax.swing.JButton();
        BtnCard5 = new javax.swing.JButton();
        BtnCard6 = new javax.swing.JButton();
        BtnCard7 = new javax.swing.JButton();
        BtnCard8 = new javax.swing.JButton();
        BtnCard9 = new javax.swing.JButton();
        BtnCard10 = new javax.swing.JButton();
        BtnCard11 = new javax.swing.JButton();
        BtnCard12 = new javax.swing.JButton();
        BtnCard13 = new javax.swing.JButton();
        BtnCard14 = new javax.swing.JButton();
        BtnCard15 = new javax.swing.JButton();
        BtnCard16 = new javax.swing.JButton();
        BtnCard17 = new javax.swing.JButton();
        BtnCard18 = new javax.swing.JButton();
        BtnCard19 = new javax.swing.JButton();
        BtnCard20 = new javax.swing.JButton();
        BtnCard21 = new javax.swing.JButton();
        BtnCard22 = new javax.swing.JButton();
        BtnCard23 = new javax.swing.JButton();
        BtnCard24 = new javax.swing.JButton();
        BtnCard25 = new javax.swing.JButton();
        BtnCard26 = new javax.swing.JButton();
        BtnCard27 = new javax.swing.JButton();
        BtnCard28 = new javax.swing.JButton();
        BtnCard29 = new javax.swing.JButton();
        BtnCard30 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thẻ định danh");

        jPanel1.setLayout(new java.awt.GridLayout(0, 6, 5, 5));

        BtnCard1.setBackground(new java.awt.Color(102, 255, 102));
        BtnCard1.setText("Card #1");
        BtnCard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCard1ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCard1);

        BtnCard2.setBackground(new java.awt.Color(102, 255, 102));
        BtnCard2.setText("Card #2");
        jPanel1.add(BtnCard2);

        BtnCard3.setText("Card #3");
        jPanel1.add(BtnCard3);

        BtnCard4.setBackground(new java.awt.Color(102, 255, 102));
        BtnCard4.setText("Card #4");
        jPanel1.add(BtnCard4);

        BtnCard5.setText("Card #5");
        jPanel1.add(BtnCard5);

        BtnCard6.setText("Card #6");
        jPanel1.add(BtnCard6);

        BtnCard7.setText("Card #7");
        jPanel1.add(BtnCard7);

        BtnCard8.setText("Card #8");
        jPanel1.add(BtnCard8);

        BtnCard9.setBackground(new java.awt.Color(102, 255, 102));
        BtnCard9.setText("Card #9");
        jPanel1.add(BtnCard9);

        BtnCard10.setText("Card #10");
        BtnCard10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCard10ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCard10);

        BtnCard11.setBackground(new java.awt.Color(102, 255, 102));
        BtnCard11.setText("Card #11");
        jPanel1.add(BtnCard11);

        BtnCard12.setBackground(new java.awt.Color(102, 255, 102));
        BtnCard12.setText("Card #12");
        jPanel1.add(BtnCard12);

        BtnCard13.setText("Card #13");
        jPanel1.add(BtnCard13);

        BtnCard14.setText("Card #14");
        jPanel1.add(BtnCard14);

        BtnCard15.setText("Card #15");
        BtnCard15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCard15ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCard15);

        BtnCard16.setText("Card #16");
        BtnCard16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCard16ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCard16);

        BtnCard17.setText("Card #17");
        jPanel1.add(BtnCard17);

        BtnCard18.setText("Card #18");
        jPanel1.add(BtnCard18);

        BtnCard19.setText("Card #19");
        jPanel1.add(BtnCard19);

        BtnCard20.setText("Card #20");
        jPanel1.add(BtnCard20);

        BtnCard21.setText("Card #21");
        jPanel1.add(BtnCard21);

        BtnCard22.setText("Card #22");
        jPanel1.add(BtnCard22);

        BtnCard23.setText("Card #23");
        jPanel1.add(BtnCard23);

        BtnCard24.setText("Card #24");
        jPanel1.add(BtnCard24);

        BtnCard25.setText("Card #25");
        jPanel1.add(BtnCard25);

        BtnCard26.setText("Card #26");
        jPanel1.add(BtnCard26);

        BtnCard27.setText("Card #27");
        jPanel1.add(BtnCard27);

        BtnCard28.setText("Card #28");
        jPanel1.add(BtnCard28);

        BtnCard29.setText("Card #29");
        jPanel1.add(BtnCard29);

        BtnCard30.setText("Card #30");
        jPanel1.add(BtnCard30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCard10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCard10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCard10ActionPerformed

    private void BtnCard15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCard15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCard15ActionPerformed

    private void BtnCard16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCard16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCard16ActionPerformed

    private void BtnCard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCard1ActionPerformed
       openBillDialog();
    }//GEN-LAST:event_BtnCard1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaleJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaleJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaleJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaleJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SaleJDialog dialog = new SaleJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCard1;
    private javax.swing.JButton BtnCard10;
    private javax.swing.JButton BtnCard11;
    private javax.swing.JButton BtnCard12;
    private javax.swing.JButton BtnCard13;
    private javax.swing.JButton BtnCard14;
    private javax.swing.JButton BtnCard15;
    private javax.swing.JButton BtnCard16;
    private javax.swing.JButton BtnCard17;
    private javax.swing.JButton BtnCard18;
    private javax.swing.JButton BtnCard19;
    private javax.swing.JButton BtnCard2;
    private javax.swing.JButton BtnCard20;
    private javax.swing.JButton BtnCard21;
    private javax.swing.JButton BtnCard22;
    private javax.swing.JButton BtnCard23;
    private javax.swing.JButton BtnCard24;
    private javax.swing.JButton BtnCard25;
    private javax.swing.JButton BtnCard26;
    private javax.swing.JButton BtnCard27;
    private javax.swing.JButton BtnCard28;
    private javax.swing.JButton BtnCard29;
    private javax.swing.JButton BtnCard3;
    private javax.swing.JButton BtnCard30;
    private javax.swing.JButton BtnCard4;
    private javax.swing.JButton BtnCard5;
    private javax.swing.JButton BtnCard6;
    private javax.swing.JButton BtnCard7;
    private javax.swing.JButton BtnCard8;
    private javax.swing.JButton BtnCard9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
